//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.Revenues = new HashSet<Revenue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CardsId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> PackedId { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Order Order { get; set; }
        public virtual Packet Packet { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenue> Revenues { get; set; }
    }
}
